const fs = require('fs');
const path = require('path');

// Attempt to load .env for local development security
// This ensures secrets are loaded from .env instead of being hardcoded
if (fs.existsSync(path.join(process.cwd(), '.env'))) {
    try {
        require('dotenv').config();
    } catch (error) {
        // dotenv might not be installed, proceed without it
    }
}

const {
    GOOGLE_SERVICES_JSON,
    GOOGLE_SERVICE_INFO_PLIST,
    googlemapsapikey,
    resendapikey,
    googleiosclientid,
    googleandroidclientid,
    expopublicfirebaseapikey,
    expopublicfirebaseauthdomain,
    expopublicfirebaseprojectid,
    expopublicfirebasestoragebucket,
    expopublicfirebasemessagingsenderid,
    expopublicfirebaseappid,
    expopublicfirebasemeasurementid
} = process.env;

// During an EAS build, all secrets must be present.
if (process.env.EAS_BUILD) {
    if (!googlemapsapikey) {
        throw new Error("Build failed: Missing googlemapsapikey in EAS secrets for this profile.");
    }
    if (!resendapikey) {
        throw new Error("Build failed: Missing resendapikey in EAS secrets for this profile.");
    }
    if (!googleiosclientid) {
        throw new Error("Build failed: Missing googleiosclientid in EAS secrets for this profile.");
    }
    if (!googleandroidclientid) {
        throw new Error("Build failed: Missing googleandroidclientid in EAS secrets for this profile.");
    }
    if (!expopublicfirebaseapikey) {
        throw new Error("Build failed: Missing a Firebase API key in EAS secrets for this profile.");
    }
    // Add checks for all other required Firebase keys
    const requiredFirebaseKeys = [
        'expopublicfirebaseauthdomain', 'expopublicfirebaseprojectid',
        'expopublicfirebasestoragebucket', 'expopublicfirebasemessagingsenderid',
        'expopublicfirebaseappid', 'expopublicfirebasemeasurementid'
    ];
    for (const key of requiredFirebaseKeys) {
        if (!process.env[key]) {
            console.error(`❌ Missing secret: ${key}`);
            throw new Error(`Build failed: Missing ${key} in EAS secrets for this profile.`);
        }
    }
}

if (GOOGLE_SERVICES_JSON) {
    try {
        const decoded = Buffer.from(GOOGLE_SERVICES_JSON, 'base64').toString('utf8');

        // Validate JSON to catch encoding errors early
        try {
            JSON.parse(decoded);
        } catch (e) {
            throw new Error("GOOGLE_SERVICES_JSON is not valid JSON. Ensure the secret is Base64 encoded.");
        }

        // Write to root (standard for Expo Managed)
        fs.writeFileSync(path.join(process.cwd(), 'google-services.json'), decoded);
        console.log('✅ Created google-services.json');

        // Also write to android/app if the android folder exists (Bare workflow / Prebuild compatibility)
        if (fs.existsSync(path.join(process.cwd(), 'android'))) {
            const androidAppPath = path.join(process.cwd(), 'android', 'app');
            fs.mkdirSync(androidAppPath, { recursive: true });
            fs.writeFileSync(path.join(androidAppPath, 'google-services.json'), decoded);
            console.log('✅ Created android/app/google-services.json');
        }
    } catch (error) {
        console.error('❌ Error creating google-services.json:', error);
        process.exit(1);
    }
}

try {
    const content = `// This file is generated by scripts/create-secrets.js
export const GOOGLE_MAPS_API_KEY = '${googlemapsapikey || ''}';
export const RESEND_API_KEY = '${resendapikey || ''}';
export const GOOGLE_IOS_CLIENT_ID = '${googleiosclientid || ''}';
export const GOOGLE_ANDROID_CLIENT_ID = '${googleandroidclientid || ''}';
export const FIREBASE_API_KEY = '${expopublicfirebaseapikey || ''}';
export const FIREBASE_AUTH_DOMAIN = '${expopublicfirebaseauthdomain || ''}';
export const FIREBASE_PROJECT_ID = '${expopublicfirebaseprojectid || ''}';
export const FIREBASE_STORAGE_BUCKET = '${expopublicfirebasestoragebucket || ''}';
export const FIREBASE_MESSAGING_SENDER_ID = '${expopublicfirebasemessagingsenderid || ''}';
export const FIREBASE_APP_ID = '${expopublicfirebaseappid || ''}';
export const FIREBASE_MEASUREMENT_ID = '${expopublicfirebasemeasurementid || ''}';
`;
    const libDir = path.join(process.cwd(), 'lib');
    if (!fs.existsSync(libDir)) {
        fs.mkdirSync(libDir, { recursive: true });
    }
    fs.writeFileSync(path.join(process.cwd(), 'lib', 'secrets.ts'), content);
    console.log('✅ Created lib/secrets.ts');
} catch (error) {
    console.error('❌ Error creating lib/secrets.ts:', error);
    process.exit(1);
}

if (GOOGLE_SERVICE_INFO_PLIST) {
    try {
        const decoded = Buffer.from(GOOGLE_SERVICE_INFO_PLIST, 'base64').toString('utf8');
        fs.writeFileSync(path.join(process.cwd(), 'GoogleService-Info.plist'), decoded);
        console.log('✅ Created GoogleService-Info.plist');
    } catch (error) {
        console.error('❌ Error creating GoogleService-Info.plist:', error);
        process.exit(1);
    }
}